<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Management.Application\Management.Application.csproj" />
    <ProjectReference Include="..\Management.Infrastructure\Management.Infrastructure.csproj" />
    <ProjectReference Include="..\ManagementDomain\Management.Domain.csproj" />
  </ItemGroup>

</Project>
